<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success-openpay-banks">

    <?php if ($block->getOrderId()): ?>
        <?php if ($block->getCanViewOrder()) : ?>
            <p><?php echo __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php endif; ?>
        <p> Método de Pago <b><?php echo $block->getPaymentMethod(); ?> </b></p>
        <?php if (isset($_SESSION['pdf_url'])): ?>
            <div style="width: 70%">                
                <iframe id="pdf" src="<?php echo $_SESSION["pdf_url"] ?>" style="width:100%; height:950px;" frameborder="0"></iframe>    
            </div>  
        <?php endif; ?>  

    <?php endif; ?>
    
</div>
