<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php /** @var $block \Openpay\Banks\Block\Onepage\Success */ ?>
<div class="checkout-success">
    <?php if ($block->getOrderId()): ?>
        <?php if (isset($_SESSION['pdf_url'])): ?>
            <div style="width: 70%">                
                <iframe id="pdf" src="<?php echo $_SESSION["pdf_url"] ?>" style="width:100%; height:950px;" frameborder="0"></iframe>    
            </div>  
        <?php endif; ?>
    <?php endif; ?>
</div>